<template>
	<div class="tags">
        <ul>
            <li>
                <span>
                    C
                </span>
            </li>
            <li>
                <span>
                    PHP
                </span>
            </li>
            <li>
                <span>
                    Python
                </span>
            </li>
            <li>
                <span>
                    Java
                </span>
            </li>
            <li>
                <span>
                    Spring MVC
                </span>
            </li>
            <li>
                <span>
                    Springboot
                </span>
            </li>
            <li>
                <span>
                    Jersey
                </span>
            </li>
            <li>
                <span>
                    HTML
                </span>
            </li>
            <li>
                <span>
                    CSS
                </span>
            </li>
            <li>
                <span>
                    Javascript
                </span>
            </li>
            <li>
                <span>
                    Node JS
                </span>
            </li>
            <li>
                <span>
                    JQuery
                </span>
            </li>
            <li>
                <span>
                    AngularJS
                </span>
            </li>
            <li>
                <span>
                    Vue JS
                </span>
            </li>
            <li>
                <span>
                    Swift
                </span>
            </li>
            <li>
                <span>
                    Docker
                </span>
            </li>
            <li>
                <span>
                    nginx
                </span>
            </li>
            <li>
                <span>
                    apache
                </span>
            </li>
            <li>
                <span>
                    unix
                </span>
            </li>
            <li>
                <span>
                    osx
                </span>
            </li>
            <li>
                <span>
                    SQL
                </span>
            </li>
            <li>
                <span>
                    Postgresql
                </span>
            </li>
            <li>
                <span>
                    Oracle
                </span>
            </li>
            <li>
                <span>
                    REST
                </span>
            </li>
            <li>
                <span>
                    git
                </span>
            </li>
            <li>
                <span>
                    mercurial
                </span>
            </li>
            <li>
                <span>
                    Jenkins
                </span>
            </li>
            <li>
                <span>
                    Salesforce
                </span>
            </li>
        </ul>
    </div>
</template>